[jenkins]
jenkins_master ansible_host=93.77.183.212 ansible_user=ubuntu ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[nexus]
nexus_server ansible_host=111.88.250.135 ansible_user=ubuntu ansible_ssh_common_args='-o StrictHostKeyChecking=no'
