[webservers]
web-a ansible_host=192.168.10.23
web-b ansible_host=192.168.20.10

[bastion]
bastion-vm ansible_host=158.160.117.132

[webservers:vars]
ansible_ssh_common_args='-o ForwardAgent=yes -o StrictHostKeyChecking=no -o ProxyCommand="ssh -W %h:%p ubuntu@158.160.117.132 -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no"'
ansible_user=ubuntu
